# Generated by Django 5.2.7 on 2025-11-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxrecord',
            name='created_at',
        ),
        migrations.AddField(
            model_name='taxrecord',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
